blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Forum Artur Home
    url: https://forum.arturhome.pl/t/integracja-energy-hub-poland-dawniej-pge-dynamic-energy/16152
    about: Masz pytanie dotyczÄ…ce konfiguracji? Zadaj je na polskim forum.
  - name: ğŸ“– Dokumentacja (README)
    url: https://github.com/AllonGit/energy_hub_poland#readme
    about: SprawdÅº instrukcjÄ™ instalacji i najczÄ™stsze problemy.
